// shared/lugares.js
const LugaresData = [
    // --- TURISMO / CENTRO HISTÓRICO ---
    {
        id: 2,
        nombre: 'Centro Histórico',
        icono: '🏛️',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Patrimonio Cultural de la Humanidad. Arquitectura colonial espectacular.',
        rating: 4.9,
        precio: '$10',
        distancia: '0 km',
        puntos: 10,
        categoria: 'turismo',
        coords: { top: '50%', left: '50%' }
    },
    {
        id: 101,
        nombre: 'Plaza Grande',
        icono: '⛲',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'El corazón de la ciudad, rodeada de poderes del estado.',
        rating: 4.8,
        precio: '$10',
        distancia: '0.1 km',
        puntos: 10,
        categoria: 'turismo',
        coords: { top: '51%', left: '50%' }
    },
    {
        id: 4,
        nombre: 'Calle La Ronda',
        icono: '🎻',
        imagen: '../assets/la_ronda.jpg',
        descripcion: 'Calle tradicional llena de vida, leyendas y oficios tradicionales.',
        rating: 4.7,
        precio: '$15',
        distancia: '1.5 km',
        puntos: 10,
        categoria: 'turismo',
        coords: { top: '75%', left: '70%' }
    },
    {
        id: 102,
        nombre: 'Plaza San Francisco',
        icono: '🕊️',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Imponente plaza de piedra volcánica frente a la iglesia.',
        rating: 4.8,
        precio: '$10',
        distancia: '0.5 km',
        puntos: 10,
        categoria: 'turismo',
        coords: { top: '60%', left: '42%' }
    },
    {
        id: 103,
        nombre: 'Palacio de Carondelet',
        icono: '👑',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Sede del Gobierno Nacional. Historia republicana.',
        rating: 4.7,
        precio: '$10',
        distancia: '0.1 km',
        puntos: 10,
        categoria: 'turismo',
        coords: { top: '51%', left: '48%' }
    },
    {
        id: 104,
        nombre: 'Teatro Nacional Sucre',
        icono: '🎭',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Principal escenario de las artes escénicas. Arquitectura neoclásica.',
        rating: 4.8,
        precio: '$25',
        distancia: '0.8 km',
        puntos: 10,
        categoria: 'turismo',
        coords: { top: '40%', left: '55%' }
    },

    // --- IGLESIAS EMBLEMÁTICAS ---
    {
        id: 6,
        nombre: 'Iglesia de la Compañía',
        icono: '✝️',
        imagen: '../assets/iglesia_compania.jpg',
        descripcion: 'Joya del barroco latinoamericano, cubierta de oro.',
        rating: 5.0,
        precio: '$12',
        distancia: '0.3 km',
        puntos: 10,
        categoria: 'iglesias',
        coords: { top: '55%', left: '67%' }
    },
    {
        id: 105,
        nombre: 'Iglesia de San Francisco',
        icono: '⛪',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Conjunto arquitectónico de gran valor histórico.',
        rating: 4.8,
        precio: '$10',
        distancia: '0.5 km',
        puntos: 10,
        categoria: 'iglesias',
        coords: { top: '48%', left: '49%' }
    },
    {
        id: 7,
        nombre: 'Basílica del Voto Nacional',
        icono: '🏰',
        imagen: '../assets/basilica_voto_nacional.jpg',
        descripcion: 'Templo neogótico más grande del Ecuador.',
        rating: 4.9,
        precio: '$15',
        distancia: '1.0 km',
        puntos: 10,
        categoria: 'iglesias',
        coords: { top: '27%', left: '60%' }
    },
    {
        id: 106,
        nombre: 'Iglesia de Santo Domingo',
        icono: '⛪',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Posee una impresionante, rica e histórica decoración.',
        rating: 4.7,
        precio: '$10',
        distancia: '0.6 km',
        puntos: 10,
        categoria: 'iglesias',
        coords: { top: '65%', left: '55%' }
    },
    {
        id: 107,
        nombre: 'Capilla de Cantuña',
        icono: '🧱',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Lugar de la famosa leyenda del atrio de San Francisco.',
        rating: 4.9,
        precio: '$10',
        distancia: '0.5 km',
        puntos: 10,
        categoria: 'iglesias',
        coords: { top: '61%', left: '40%' }
    },

    // --- ÍCONOS TURÍSTICOS ---
    {
        id: 8,
        nombre: 'El Panecillo',
        icono: '🥖',
        imagen: '../assets/el_panecillo.jpg',
        descripcion: 'Virgen de Quito. Monumento gigante de aluminio.',
        rating: 4.6,
        precio: '$10',
        distancia: '2.0 km',
        puntos: 10,
        categoria: 'iconos',
        coords: { top: '65%', left: '50%' }
    },
    {
        id: 1,
        nombre: 'Mitad del Mundo',
        icono: '🌍',
        imagen: '../assets/mitad_mundo.png',
        descripcion: 'Ciudad Mitad del Mundo. Latitud 0-0-0.',
        rating: 4.8,
        precio: '$50',
        distancia: '25 km',
        puntos: 10,
        categoria: 'iconos',
        coords: { top: '17%', left: '27%' }
    },
    {
        id: 3,
        nombre: 'Teleférico',
        icono: '🚡',
        imagen: '../assets/teleferico.png',
        descripcion: 'Mirador Cruz Loma. Naturaleza y vista única.',
        rating: 4.9,
        precio: '$45',
        distancia: '5.0 km',
        puntos: 10,
        categoria: 'iconos',
        coords: { top: '20%', left: '80%' }
    },
    {
        id: 108,
        nombre: 'Mirador del Itchimbía',
        icono: '🖼️',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Vista de 360 grados y Palacio de Cristal.',
        rating: 4.8,
        precio: '$15',
        distancia: '2.5 km',
        puntos: 10,
        categoria: 'iconos',
        coords: { top: '40%', left: '80%' }
    },
    {
        id: 109,
        nombre: 'Intiñán Museum',
        icono: '🌞',
        imagen: '../assets/mitad_mundo.png',
        descripcion: 'Museo de sitio, experimentos solares y cultura.',
        rating: 4.8,
        precio: '$25',
        distancia: '25 km',
        puntos: 10,
        categoria: 'iconos',
        coords: { top: '12%', left: '55%' }
    },

    // --- MUSEOS ---
    {
        id: 110,
        nombre: 'Museo de la Ciudad',
        icono: '🏺',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Antiguo Hospital San Juan de Dios convertido en museo.',
        rating: 4.7,
        precio: '$14',
        distancia: '0.8 km',
        puntos: 10,
        categoria: 'museos',
        coords: { top: '70%', left: '60%' }
    },
    {
        id: 111,
        nombre: 'Museo del Agua (Yaku)',
        icono: '💧',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Museo interactivo para valorar el recurso hídrico.',
        rating: 4.8,
        precio: '$14',
        distancia: '1.2 km',
        puntos: 10,
        categoria: 'museos',
        coords: { top: '65%', left: '30%' }
    },
    {
        id: 112,
        nombre: 'Museo Nacional (MuNa)',
        icono: '🇪🇨',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Memoria histórica y bienes culturales del Ecuador.',
        rating: 4.8,
        precio: '$10',
        distancia: '3.0 km',
        puntos: 10,
        categoria: 'museos',
        coords: { top: '15%', left: '80%' }
    },

    // --- MIRADORES ---
    {
        id: 113,
        nombre: 'Mirador del Panecillo',
        icono: '👀',
        imagen: '../assets/el_panecillo.jpg',
        descripcion: 'El balcón natural de la ciudad.',
        rating: 4.6,
        precio: '$10',
        distancia: '2.0 km',
        puntos: 10,
        categoria: 'miradores',
        coords: { top: '85%', left: '25%' }
    },
    {
        id: 114,
        nombre: 'Mirador de Guangüiltagua',
        icono: '🌲',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'En el Parque Metropolitano Norte, pulmón de la ciudad.',
        rating: 4.8,
        precio: '$10',
        distancia: '8 km',
        puntos: 10,
        categoria: 'miradores',
        coords: { top: '5%', left: '90%' }
    },
    {
        id: 115,
        nombre: 'Mirador de Guápulo',
        icono: '🏘️',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Vista hacia los valles y la iglesia de Guápulo.',
        rating: 4.9,
        precio: '$12',
        distancia: '5 km',
        puntos: 10,
        categoria: 'miradores',
        coords: { top: '20%', left: '90%' }
    },

    // --- CULTURA ---
    {
        id: 116,
        nombre: 'Barrio La Floresta',
        icono: '🎨',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Arte urbano, gastronomía y diseño.',
        rating: 4.7,
        precio: '$15',
        distancia: '4 km',
        puntos: 10,
        categoria: 'cultura',
        coords: { top: '63%', left: '22%' }
    },
    {
        id: 117,
        nombre: 'Barrio La Ronda',
        icono: '🏮',
        imagen: '../assets/la_ronda.jpg',
        descripcion: 'Tradición y bohemia en el centro histórico.',
        rating: 4.7,
        precio: '$20',
        distancia: '1.5 km',
        puntos: 10,
        categoria: 'cultura',
        coords: { top: '75%', left: '72%' }
    },
    {
        id: 118,
        nombre: 'Mercado Artesanal',
        icono: '🧶',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Artesanías de todas las regiones del país.',
        rating: 4.6,
        precio: '$25',
        distancia: '3 km',
        puntos: 10,
        categoria: 'cultura',
        coords: { top: '35%', left: '19%' }
    },

    // --- EXTRAS ---
    {
        id: 119,
        nombre: 'Parque Rumipamba',
        icono: '🏺',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Parque arqueológico y ecológico.',
        rating: 4.5,
        precio: '$10',
        distancia: '6 km',
        puntos: 10,
        categoria: 'extras',
        coords: { top: '10%', left: '10%' }
    },
    {
        id: 120,
        nombre: 'García Moreno',
        icono: '✝️',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'La Calle de las Siete Cruces, historia pura.',
        rating: 4.8,
        precio: '$12',
        distancia: '0.2 km',
        puntos: 10,
        categoria: 'extras',
        coords: { top: '55%', left: '50%' }
    },

    // --- RESTAURANTES ---
    {
        id: 10,
        nombre: 'Hasta la Vuelta Señor',
        icono: '🥘',
        imagen: '../assets/hasta_la_vuelta_senor.jpg',
        descripcion: 'Sabor tradicional en el Palacio Arzobispal.',
        rating: 4.7,
        precio: '$35',
        distancia: '0.2 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '52%', left: '46%' }
    },
    {
        id: 11,
        nombre: 'Vista Hermosa',
        icono: '🍷',
        imagen: '../assets/vista_hermosa.png',
        descripcion: 'Panorámica 360 del Centro Histórico.',
        rating: 4.8,
        precio: '$45',
        distancia: '0.5 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '71%', left: '80%' }
    },
    {
        id: 9,
        nombre: 'Café Plaza Grande',
        icono: '☕',
        imagen: '../assets/cafe_plaza_grande.png',
        descripcion: 'Tradición y lujo en la Plaza Grande.',
        rating: 4.7,
        precio: '$40',
        distancia: '0.1 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '50%', left: '48%' }
    },
    {
        id: 121,
        nombre: 'El Ventanal',
        icono: '🍽️',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Gastronomía ecuatoriana con vista.',
        rating: 4.7,
        precio: '$50',
        distancia: '1.0 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '40%', left: '30%' }
    },
    {
        id: 122,
        nombre: 'Restaurantes La Ronda',
        icono: '🍲',
        imagen: '../assets/la_ronda.jpg',
        descripcion: 'Varios locales con comida típica y canelazos.',
        rating: 4.6,
        precio: '$25',
        distancia: '1.5 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '76%', left: '71%' }
    },
    {
        id: 123,
        nombre: 'Sanduches Plaza Grande',
        icono: '🥪',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Sabor tradicional e histórico.',
        rating: 4.6,
        precio: '$12',
        distancia: '0.1 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '52%', left: '49%' }
    },
    {
        id: 124,
        nombre: 'Dulcería Colonial',
        icono: '🍬',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Dulces de antaño.',
        rating: 4.8,
        precio: '$10',
        distancia: '0.3 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '55%', left: '52%' }
    },
    {
        id: 125,
        nombre: 'El Cráter',
        icono: '🌋',
        imagen: '../assets/mitad_mundo.png',
        descripcion: 'Restaurante en el borde del volcán Pululahua.',
        rating: 4.8,
        precio: '$45',
        distancia: '20 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '5%', left: '40%' }
    },
    {
        id: 126,
        nombre: 'Theatrum',
        icono: '🎭',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Cocina mediterránea y ecuatoriana.',
        rating: 4.8,
        precio: '$50',
        distancia: '0.8 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '41%', left: '55%' }
    },
    {
        id: 127,
        nombre: 'Café Tianguez',
        icono: '☕',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Bajo el atrio de San Francisco.',
        rating: 4.5,
        precio: '$20',
        distancia: '0.5 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '61%', left: '41%' }
    },
    {
        id: 128,
        nombre: 'Zazu',
        icono: '🍾',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Relais & Châteaux.',
        rating: 4.9,
        precio: '$50',
        distancia: '5 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '15%', left: '85%' }
    },
    {
        id: 129,
        nombre: 'URKO',
        icono: '🍃',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Cocina Local.',
        rating: 4.9,
        precio: '$50',
        distancia: '4 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '32%', left: '86%' }
    },
    {
        id: 130,
        nombre: 'Nuema',
        icono: '🌟',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Reconocido en 50 Best Restaurants.',
        rating: 5.0,
        precio: '$50',
        distancia: '6 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '10%', left: '80%' }
    },
    {
        id: 131,
        nombre: 'ZFood',
        icono: '🐟',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Pescadería gourmet.',
        rating: 4.7,
        precio: '$45',
        distancia: '5 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '12%', left: '80%' }
    },
    {
        id: 132,
        nombre: 'Quitu Identidad',
        icono: '🌽',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Identidad culinaria.',
        rating: 4.7,
        precio: '$40',
        distancia: '4 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '33%', left: '85%' }
    },
    {
        id: 133,
        nombre: 'Café Mosaico',
        icono: '🏙️',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Balcón de Quito.',
        rating: 4.7,
        precio: '$30',
        distancia: '2.5 km',
        puntos: 10,
        categoria: 'restaurantes',
        coords: { top: '42%', left: '82%' }
    },

    // --- HUECAS ---
    {
        id: 134,
        nombre: 'La Casa de la Fritada',
        icono: '🐷',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Hueca tradicional.',
        rating: 4.6,
        precio: '$15',
        distancia: '3 km',
        puntos: 10,
        categoria: 'huecas',
        coords: { top: '35%', left: '70%' }
    },
    {
        id: 135,
        nombre: 'Fritadas Doña Mary',
        icono: '🐷',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Sabor de siempre.',
        rating: 4.5,
        precio: '$12',
        distancia: '2 km',
        puntos: 10,
        categoria: 'huecas',
        coords: { top: '30%', left: '60%' }
    },
    {
        id: 136,
        nombre: 'El Rancho de Juancho',
        icono: '🍖',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Comida típica.',
        rating: 4.5,
        precio: '$18',
        distancia: '10 km',
        puntos: 10,
        categoria: 'huecas',
        coords: { top: '8%', left: '70%' }
    },
    {
        id: 137,
        nombre: 'Hornados de Ricaurte',
        icono: '🍖',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Plato tradicional.',
        rating: 4.7,
        precio: '$14',
        distancia: '10 km',
        puntos: 10,
        categoria: 'huecas',
        coords: { top: '5%', left: '70%' }
    },
    {
        id: 138,
        nombre: 'Hornados de Calderón',
        icono: '🍖',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Famosos en el norte.',
        rating: 4.7,
        precio: '$15',
        distancia: '15 km',
        puntos: 10,
        categoria: 'huecas',
        coords: { top: '2%', left: '50%' }
    },
    {
        id: 139,
        nombre: 'Fritadas Guangüiltagua',
        icono: '🐷',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Cerca del parque.',
        rating: 4.6,
        precio: '$12',
        distancia: '8 km',
        puntos: 10,
        categoria: 'huecas',
        coords: { top: '6%', left: '90%' }
    },
    {
        id: 140,
        nombre: 'Hornado de la Michelena',
        icono: '🍖',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Sabor del sur.',
        rating: 4.7,
        precio: '$10',
        distancia: '6 km',
        puntos: 10,
        categoria: 'huecas',
        coords: { top: '90%', left: '40%' }
    },
    {
        id: 141,
        nombre: 'Sanduches de la 24',
        icono: '🥪',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Pernil con sabor a historia.',
        rating: 4.6,
        precio: '$10',
        distancia: '1.2 km',
        puntos: 10,
        categoria: 'huecas',
        coords: { top: '70%', left: '50%' }
    },
    {
        id: 142,
        nombre: 'Empanadas San Francisco',
        icono: '🥟',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Morocho crocante.',
        rating: 4.8,
        precio: '$5',
        distancia: '0.5 km',
        puntos: 10,
        categoria: 'huecas',
        coords: { top: '62%', left: '43%' }
    },
    {
        id: 143,
        nombre: 'Quimbolitos del Ejido',
        icono: '🍰',
        imagen: '../assets/centro_historico.jpg',
        descripcion: 'Tradición quiteña.',
        rating: 4.7,
        precio: '$10',
        distancia: '2 km',
        puntos: 10,
        categoria: 'huecas',
        coords: { top: '32%', left: '60%' }
    }
];